ARM_LOGGER:
  CONSOLE:
    LEVEL: info
    LOGGER_NAME: arm_logger
    USE: true
  FILE:
    LEVEL: debug
    LOGGER_NAME: logs/deoxys_control_arm_program.log
    USE: true
CONTROL:
  POLICY_RATE: 20
  STATE_PUBLISHER_RATE: 100
  TRAJ_RATE: 500
  ZMQ_NOBLOCK: true
GRIPPER_LOGGER:
  CONSOLE:
    LEVEL: info
    LOGGER_NAME: gripper_logger
    USE: true
  FILE:
    LEVEL: debug
    LOGGER_NAME: logs/deoxys_control_gripper_program.log
    USE: true
NUC:
  GRIPPER_PUB_PORT: 5558
  GRIPPER_SUB_PORT: 16350
  IP: 100.126.30.132
  NAME: grail
  PUB_PORT: 5556
  SUB_PORT: 16349
PC:
  IP: 100.126.30.132
  NAME: grail
ROBOT:
  IP: 172.16.0.2
